/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sample_rescale_Rescale */

#ifndef _Included_com_sample_rescale_Rescale
#define _Included_com_sample_rescale_Rescale
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sample_rescale_Rescale
 * Method:    native_scale
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;IDD)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_sample_rescale_Rescale_native_1scale
  (JNIEnv *, jclass, jobject, jobject, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
